//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleCMS {
	
	
	public partial class SiteOne {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.WebControls.Menu Topnav;
		
		protected System.Web.UI.WebControls.DataList leftNavList;
		
		protected System.Web.UI.WebControls.DataList leftNavItems;
		
		protected System.Web.UI.WebControls.Label testLabel;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder contentPlaceHolder;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
	}
}
